### ISSUE TITLE
googleapiclient.errors.ResumableUploadError: <HttpError 401 "Unauthorized">

### ISSUE THREAD

**Issue by ytyng** [tokland/youtube-upload#10]
$ youtube-upload --title="eggs" --location="=" --client-secrets=client_secret.json test.mov

Using client secrets: client_secret.json
Using credentials file: /Users/ytyng/.youtube-upload-credentials.json
Start upload: test.mov (eggs)
Traceback (most recent call last):
  File "/Users/ytyng/.virtualenvs/d17/bin/youtube-upload", line 164, in <module>
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/Users/ytyng/.virtualenvs/d17/lib/python2.7/site-packages/youtube_upload/lib.py", line 21, in catch_exceptions
    fun(*args, **kwargs)
  File "/Users/ytyng/.virtualenvs/d17/bin/youtube-upload", line 161, in main
    run_main(parser, options, args)
  File "/Users/ytyng/.virtualenvs/d17/bin/youtube-upload", line 124, in run_main
    video_id = upload_video(youtube, options, video_path, len(args), index)
  File "/Users/ytyng/.virtualenvs/d17/bin/youtube-upload", line 100, in upload_video
    progress_callback=progress.callback, chunksize=16*1024)
  File "/Users/ytyng/.virtualenvs/d17/lib/python2.7/site-packages/youtube_upload/upload_video.py", line 35, in upload
    return lib.retriable_exceptions(upload_fun, RETRIABLE_EXCEPTIONS, max_retries=10)
  File "/Users/ytyng/.virtualenvs/d17/lib/python2.7/site-packages/youtube_upload/lib.py", line 45, in retriable_exceptions
    return fun()
  File "/Users/ytyng/.virtualenvs/d17/lib/python2.7/site-packages/youtube_upload/upload_video.py", line 34, in <lambda>
    upload_fun = lambda: _upload_to_request(request, progress_callback)
  File "/Users/ytyng/.virtualenvs/d17/lib/python2.7/site-packages/youtube_upload/upload_video.py", line 20, in _upload_to_request
    status, response = request.next_chunk()
  File "/Users/ytyng/.virtualenvs/d17/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/ytyng/.virtualenvs/d17/lib/python2.7/site-packages/googleapiclient/http.py", line 808, in next_chunk
    raise ResumableUploadError(resp, content)
googleapiclient.errors.ResumableUploadError: <HttpError 401 "Unauthorized">

**Comment by tokland** [comment]
With that exception name, let's guess we have to retry. Please try: f9443740
