### ISSUE TITLE
Receiving error now trying to connect to google api

### ISSUE THREAD

**Issue by AntiNSA** [tokland/youtube-upload#104]
raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at www.googleapis.com

any ideas? Worked fine for ever :

Using client secrets: /usr/local/share/youtube_upload/client_secrets.json
Using credentials file: /root/.youtube-upload-credentials.json
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 251, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 39, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 246, in main
    run_main(parser, options, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 174, in run_main
    youtube = get_youtube_handler(options)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 160, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth/__init__.py", line 42, in get_resource
    return googleapiclient.discovery.build("youtube", "v3", http=http)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 203, in build
    cache)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 249, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 622, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1278, in _conn_request

**Comment by tokland** [comment]
Cannot reproduce. I'd check the network (DNS, ...) to make sure everything is ok.

**Comment by AntiNSA** [comment]
I found it was a DSN problem on my linode. Sorry for the fuss...
