### ISSUE TITLE
Can't Upload anymore

### ISSUE THREAD

**Issue by josbrouwer** [tokland/youtube-upload#105]
Hi, sinds this afternoon a get a error back from Youtube:

Start upload: /Users/admin/Desktop/Test.mp4
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_upload/main.py", line 251, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_upload/lib.py", line 39, in catch_exceptions
    fun(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_upload/main.py", line 246, in main
    run_main(parser, options, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_upload/main.py", line 178, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_upload/main.py", line 140, in upload_youtube_video
    request_body, progress_callback=progress.callback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_upload/upload_video.py", line 40, in upload
    RETRIABLE_EXCEPTIONS, max_retries=max_retries)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_upload/lib.py", line 71, in retriable_exceptions
    return fun()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_upload/upload_video.py", line 38, in <lambda>
    upload_fun = lambda: _upload_to_request(request, progress_callback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_upload/upload_video.py", line 22, in _upload_to_request
    status, response = request.next_chunk()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "build/bdist.macosx-10.6-intel/egg/googleapiclient/http.py", line 807, in next_chunk
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/client.py", line 633, in new_request
    self._refresh(request_orig)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/client.py", line 876, in _refresh
    self._do_refresh_request(http_request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/client.py", line 933, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: internal_failure

and i get also the message 

Check this link in your browser: https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.upload+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=911313852664-tir6o945mdn2bouorhpalkecrg23dng9.apps.googleusercontent.com&access_type=offline

Yesterday no problems, and i did not change anything.
Any idea? 

Regards Jos

**Comment by josbrouwer** [comment]
Hi,

everthing works again, probably a Youtube error :)

Regards Jos
