### ISSUE TITLE
Error after entering the verification code:

### ISSUE THREAD

**Issue by toho64** [tokland/youtube-upload#112]
I'm using Linux 64 (open suse) an python 2.7.6 and I get the following error after entering the verification code:

Traceback (most recent call last):
  File "bin/youtube-upload", line 10, in <module>
    main.run()
  File "/home/hoppe/install/suttervideo/upload/youtube-upload-master/bin/../youtube_upload/main.py", line 251, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/home/hoppe/install/suttervideo/upload/youtube-upload-master/bin/../youtube_upload/lib.py", line 39, in catch_exceptions
    fun(*args, **kwargs)
  File "/home/hoppe/install/suttervideo/upload/youtube-upload-master/bin/../youtube_upload/main.py", line 246, in main
    run_main(parser, options, args)
  File "/home/hoppe/install/suttervideo/upload/youtube-upload-master/bin/../youtube_upload/main.py", line 174, in run_main
    youtube = get_youtube_handler(options)
  File "/home/hoppe/install/suttervideo/upload/youtube-upload-master/bin/../youtube_upload/main.py", line 160, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "/home/hoppe/install/suttervideo/upload/youtube-upload-master/bin/../youtube_upload/auth/__init__.py", line 39, in get_resource
    credentials = _get_credentials(flow, storage, get_code_callback)
  File "/home/hoppe/install/suttervideo/upload/youtube-upload-master/bin/../youtube_upload/auth/__init__.py", line 32, in _get_credentials
    return _get_credentials_interactively(flow, storage, get_code_callback)
  File "/home/hoppe/install/suttervideo/upload/youtube-upload-master/bin/../youtube_upload/auth/__init__.py", line 21, in _get_credentials_interactively
    credential = flow.step2_exchange(code, http=None)
  File "/usr/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 2102, in step2_exchange
    headers=headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1075, in connect
    raise socket.error, msg
socket.error: [Errno 111] Connection refused

**Comment by tokland** [comment]
Seems a normal network error, did it persist?

**Comment by toho64** [comment]
Hi,

no, the error persists. I coded my own program in the meantime because 
of this reason.


Regards,
  Torsten

Am 21.06.2016 um 22:40 schrieb Arnau Sanchez:
> Seems a normal network error, did it persist?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tokland/youtube-upload/issues/112#issuecomment-227564952>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASlSiX7wviIZCmt748J-IdWAG7r-yENzks5qOExSgaJpZM4Ii7lI>.
>


-- 
Viele Grüße

Torsten Hoppe
torsten Hoppe Informatik
Tel:  034293 33633
Mobil:0173 964 3316
