### ISSUE TITLE
Problem on upload

### ISSUE THREAD

**Issue by digoot** [tokland/youtube-upload#123]
I installed as the description said. I created a json file with the credentials on google developer console and I provided it. When I tried to upload a video I got this error:

`Using client secrets: client_secrets.json
Using credentials file: credentials.json
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 250, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 39, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 245, in main
    run_main(parser, options, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 173, in run_main
    youtube = get_youtube_handler(options)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 159, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth/__init__.py", line 39, in get_resource
    credentials = _get_credentials(flow, storage, get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth/__init__.py", line 28, in _get_credentials
    existing_credentials = storage.get()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 420, in get
    return self.locked_get()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/file.py", line 66, in locked_get
    credentials = Credentials.new_from_json(content)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 316, in new_from_json
    module_name = data['_module']
KeyError: '_module'`

I used the file `client_secrets.json` provided. Maybe did something wrong but I couldn't guess what.

**Comment by digoot** [comment]
I should have read the closed issues.
