### ISSUE TITLE
Stuck at Starting Upload

### ISSUE THREAD

**Issue by raleighmartin123** [tokland/youtube-upload#125]
Hello, I've been trying to use youtube_upload for a while now. Having some issues. When I start to upload a video, I don't ever get to a progress bar, yet I don't get an error right away either. Its only when I interrupt the process (by control+C) that I get this long mess:

`^CTraceback (most recent call last):
  
File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()

  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 250, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))

  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 39, in catch_exceptions
    fun(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 245, in main
    run_main(parser, options, args)

  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 177, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)

  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 139, in upload_youtube_video
    request_body, progress_callback=progress.callback)

  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/upload_video.py", line 42, in upload
    RETRIABLE_EXCEPTIONS, max_retries=max_retries)

  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 71, in retriable_exceptions
    return fun()

  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/upload_video.py", line 40, in <lambda>
    upload_fun = lambda: _upload_to_request(request, progress_callback)

  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/upload_video.py", line 24, in _upload_to_request
    status, response = request.next_chunk()

  File "/home/sploit/.local/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)

  File "/home/sploit/.local/lib/python2.7/site-packages/googleapiclient/http.py", line 903, in next_chunk
    self.uri, method=self.method, body=self.body, headers=start_headers)

  File "/home/sploit/.local/lib/python2.7/site-packages/googleapiclient/http.py", line 154, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)

  File "/home/sploit/.local/lib/python2.7/site-packages/oauth2client/transport.py", line 169, in new_request
    redirections, connection_type)

  File "/home/sploit/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)

  File "/home/sploit/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)

  File "/home/sploit/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1307, in _conn_request
    response = conn.getresponse()

  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()

  File "/usr/lib/python2.7/httplib.py", line 485, in begin
    self.msg = HTTPMessage(self.fp, 0)

  File "/usr/lib/python2.7/mimetools.py", line 25, in __init__
    rfc822.Message.__init__(self, fp, seekable)

  File "/usr/lib/python2.7/rfc822.py", line 108, in __init__
    self.readheaders()

  File "/usr/lib/python2.7/httplib.py", line 319, in readheaders
    line = self.fp.readline(_MAXLINE + 1)

  File "/usr/lib/python2.7/socket.py", line 501, in readline
    n = len(data)

KeyboardInterrupt`

Furthermore my videos are making it to youtube and say that they are "processing upload", but the upload never quite starts.

I already have installed pip and googleapiclient etc. and they are all up to date.

Perhaps I shouldn't have stopped the process and am simply too impatient, however I was sure that there was supposed to be some sort of way to see that the video had started processing...

I'm still quite new to python, so if anyone spots some silly mistake or something I should change, that would be very helpful. Thanks !

**Comment by tokland** [comment]
Do you have `progressbar2` installed?

**Comment by raleighmartin123** [comment]
No I do not let my try that.

**Comment by raleighmartin123** [comment]
I believe that worked. I will return when I know for sure though. Thank you sir for your help !

**Comment by tokland** [comment]
Cool
