### ISSUE TITLE
Invalid_client

### ISSUE THREAD

**Issue by Avalarion90** [tokland/youtube-upload#13]
I getting this Error after entering the verification code:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 164, in <module>
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 21,                                                                                                                                                              in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/bin/youtube-upload", line 161, in main
    run_main(parser, options, args)
  File "/usr/local/bin/youtube-upload", line 121, in run_main
    youtube = youtube_upload.auth.get_resource(client_secrets, credentials)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth.py", line 40,                                                                                                                                                              in get_resource
    credentials = _get_credentials(flow, storage, get_code)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth.py", line 32,                                                                                                                                                              in _get_credentials
    return _get_credentials_interactively(flow, storage, get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth.py", line 21,                                                                                                                                                              in _get_credentials_interactively
    credential = flow.step2_exchange(code, http=None)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 135,                                                                                                                                                              in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 196                                                                                                                                                             4, in step2_exchange
    raise FlowExchangeError(error_msg)
oauth2client.client.FlowExchangeError: invalid_client

**Comment by tokland** [comment]
Sorry, I have no idea, never seen this error... still happening?

**Comment by tokland** [comment]
No feedback. Closing.
