### ISSUE TITLE
Error when uploading a video to an existed non-ascii utf-8 titled playlist

### ISSUE THREAD

**Issue by pthreadself** [tokland/youtube-upload#131]
when uploading a video to an already existed playlist, and the playlist's title is non-ascii utf-8(such as Chinese characters), it catches an exception:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 250, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 39, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 245, in main
    run_main(parser, options, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 187, in run_main
    title=lib.to_utf8(options.playlist), privacy=options.privacy)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/playlists.py", line 43, in add_video_to_playlist
    playlist_id = get_playlist(youtube, title) or \
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/playlists.py", line 11, in get_playlist
    if existing_playlist_title.encode("utf8") == title.encode("utf-8"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

**Comment by tokland** [comment]
One of those problems of compatibility py2/3. Hope a22db3af solves it.
