### ISSUE TITLE
IOError: [Errno 13] Permission Denied

### ISSUE THREAD

**Issue by KelDG** [tokland/youtube-upload#157]
Hi I am having trouble getting permission to upload.

1, I run the terminal line youtube-upload --title="test" vid.avi

2, Follow the given URL link to allow permissions and I am then given the verification code

3, Paste the verification code into the terminal

Then I get the error commented below.  

Apologies if this is a stupid error on my part I am quite new to Linux,  I cant see any errors other than the permission being denied, I have enabled Youtubes APIs from the channels page and have created an OAuth 2.0 client ID called youtube-upload (though I take it i'm not getting that far yet, I have tried adding in the --client-secrets=(path to my created .json file) with the same error still occurring).

Thanks for any help

> Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 251, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 42, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 245, in main
    run_main(parser, options, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 173, in run_main
    youtube = get_youtube_handler(options)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 159, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth/__init__.py", line 39, in get_resource
    credentials = _get_credentials(flow, storage, get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth/__init__.py", line 32, in _get_credentials
    return _get_credentials_interactively(flow, storage, get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth/__init__.py", line 21, in _get_credentials_interactively
    credential = flow.step2_exchange(code, http=None)
  File "build/bdist.linux-armv6l/egg/oauth2client/_helpers.py", line 133, in positional_wrapper
  File "build/bdist.linux-armv6l/egg/oauth2client/client.py", line 2047, in step2_exchange
  File "build/bdist.linux-armv6l/egg/oauth2client/transport.py", line 282, in request
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 1036, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "/usr/lib/python2.7/ssl.py", line 891, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 507, in __init__
    self._context.load_verify_locations(ca_certs)
IOError: [Errno 13] Permission denied

**Comment by userlip** [comment]
Please run `ls -lisa` in the command line in the folder where your vid.avi is

**Comment by KelDG** [comment]
Can you tell me what I should be looking for in this.  Thanks

pi@raspberrypi:~ $ ls -lisa
total 101416
136941      4 drwxr-xr-x 27 pi   pi        4096 Jan 29 20:43 .
130817      4 drwxr-xr-x  3 root root      4096 Nov 25 17:24 ..
137717      4 -rw-r--r--  1 pi   pi          69 Nov 25 18:32 .asoundrc
148308      8 -rw-------  1 pi   pi        6421 Jan 29 20:42 .bash_history
136942      4 -rw-r--r--  1 pi   pi         220 Nov 25 17:24 .bash_logout
136950      4 -rw-r--r--  1 pi   pi        3512 Nov 25 17:24 .bashrc
285749      4 drwxr-xr-x  6 pi   pi        4096 Jan 27 19:38 .cache
131163      4 -rw-r--r--  1 pi   pi         215 Jan 28 19:59 CatapultBox.py
136943      4 drwx------ 16 pi   pi        4096 Jan 28 10:37 .config
285746      4 drwx------  3 pi   pi        4096 Nov 25 18:10 .dbus
136947      4 drwxr-xr-x  2 pi   pi        4096 Nov 25 17:55 Desktop
136944      4 drwxr-xr-x  5 pi   pi        4096 Nov 25 17:55 Documents
285740      4 drwxr-xr-x  3 pi   pi        4096 Jan 29 19:30 Downloads
395566      4 drwxr-xr-x  3 pi   pi        4096 Oct  4 11:43 ffmpeg3
148319      4 drwx------  2 pi   pi        4096 Jan 29 18:30 .gconf
285762      4 drwxr-xr-x  2 pi   pi        4096 Nov 25 18:10 .gstreamer-0.10
131643      4 -rw-r--r--  1 pi   pi          26 Jan 28 10:58 .gtkrc-2.0
395646      4 drwxr-xr-x  2 pi   pi        4096 Jan 28 10:15 .idlerc
136946      4 drwxr-xr-x  3 pi   pi        4096 Nov 25 17:55 .local
148280      4 drwxr-xr-x  3 pi   pi        4096 Jan 27 20:08 .minecraft
285743      4 drwxr-xr-x  2 pi   pi        4096 Nov 25 18:10 Music
131601      4 -rw-r--r--  1 pi   pi        2772 Jan 29 20:25 New.txt
395014      4 drwxr-xr-x  4 pi   pi        4096 Jan 27 20:47 oldconffiles
285744      4 drwxr-xr-x  2 pi   pi        4096 Nov 25 18:10 Pictures
395644      4 drwxr-xr-x  2 pi   pi        4096 Jan 28 10:09 .pip
148315      4 drwx------  3 pi   pi        4096 Jan 27 19:38 .pki
136948      4 -rw-r--r--  1 pi   pi         675 Nov 25 17:24 .profile
285742      4 drwxr-xr-x  2 pi   pi        4096 Nov 25 18:10 Public
136945      4 drwxr-xr-x  2 pi   pi        4096 Nov 25 17:55 python_games
131795      4 -rw-r--r--  1 pi   pi          82 Jan 29 18:52 SendToYoutube.py
285741      4 drwxr-xr-x  2 pi   pi        4096 Nov 25 18:10 Templates
136949      4 drwxr-xr-x  3 pi   pi        4096 Jan 27 20:51 .themes
395559      4 drwx------  4 pi   pi        4096 Jan 27 21:01 .thumbnails
131350 101256 -rw-r--r--  1 pi   pi   103681448 Jan 28 19:55 vid.avi
285745      4 drwxr-xr-x  2 pi   pi        4096 Nov 25 18:10 Videos
148324      4 drwx------  3 pi   pi        4096 Jan 27 19:45 .vnc
148291      4 -rw-------  1 pi   pi          56 Jan 29 20:43 .Xauthority
130939      4 -rw-------  1 pi   pi        1369 Feb  3 10:53 .xsession-errors
130911      4 -rw-------  1 pi   pi        1369 Jan 29 18:24 .xsession-errors.old
395820      4 drwxr-xr-x  8 pi   pi        4096 Jan 29 19:32 youtube-upload-master
pi@raspberrypi:~ $

**Comment by userlip** [comment]
Maybe this will help you http://stackoverflow.com/a/29679378/6400752

**Comment by KelDG** [comment]
I managed to get it working, I had to run the command as SUDO for some reason.  Any idea why this may be the case?  Thanks everyone for the suggestions anyway :)

**Comment by kootsoop** [comment]
Closing. Was a permissions issue for user.
