### ISSUE TITLE
TypeError: decode() takes no keyword arguments

### ISSUE THREAD

**Issue by benkhouya** [tokland/youtube-upload#180]
I've got this error, using Python 2.6.6

root@snip [/usr/local/src/youtube-upload-master]# youtube-upload --title="demo" oceans.mp4 
Using client secrets: /root/.client_secrets.json
Using credentials file: /root/.youtube-upload-credentials.json
Start upload: oceans.mp4

> Traceback (most recent call last):
>   File "/usr/bin/youtube-upload", line 10, in <module>
>     main.run()
>   File "/usr/lib/python2.6/site-packages/youtube_upload/main.py", line 251, in run
>     sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
>   File "/usr/lib/python2.6/site-packages/youtube_upload/lib.py", line 42, in catch_exceptions
>     fun(*args, **kwargs)
>   File "/usr/lib/python2.6/site-packages/youtube_upload/main.py", line 247, in main
>     response = bytes.decode(error.content, encoding=lib.get_encoding()).strip()
> TypeError: decode() takes no keyword arguments

Can you fix that?
Thanks

**Comment by AndCycle** [comment]
just use python3 which will save you a lot of trouble
