### ISSUE TITLE
plz help: ssl.SSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by vigilantspb** [tokland/youtube-upload#192]
I get 

Using client secrets: /usr/local/share/youtube_upload/client_secrets.json
Using credentials file: /root/.youtube-upload-credentials.json
Traceback (most recent call last):
  File "/root/youtube-upload-master/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/root/youtube-upload-master/bin/../youtube_upload/main.py", line 250, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/root/youtube-upload-master/bin/../youtube_upload/lib.py", line 39, in catch_exceptions
    fun(*args, **kwargs)
  File "/root/youtube-upload-master/bin/../youtube_upload/main.py", line 245, in main
    run_main(parser, options, args)
  File "/root/youtube-upload-master/bin/../youtube_upload/main.py", line 173, in run_main
    youtube = get_youtube_handler(options)
  File "/root/youtube-upload-master/bin/../youtube_upload/main.py", line 159, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "/root/youtube-upload-master/bin/../youtube_upload/auth/__init__.py", line 42, in get_resource
    return googleapiclient.discovery.build("youtube", "v3", http=http)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 214, in build
    cache)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 261, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/transport.py", line 169, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1036, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

Yesterday and many many days ago everything was fine. What is possible to do with this problem? Thanks for your help!

**Comment by vigilantspb** [comment]
It works 1 time of maybe 20-30 attempts, tried many recommendations from google but no luck.
I use Python 2.7.3, and it used to be working perfectly (uploaded up to 10 videos a day for may be last year).

What is the reason, can anyone help please?

**Comment by vigilantspb** [comment]
It's ok now. Fixed by itself) May be problem on Youtube side or whatever, but now it is fine

**Comment by vigilantspb** [comment]
thank you for your help (sarcasm)
