### ISSUE TITLE
KeyError as a standart user

### ISSUE THREAD

**Issue by ezgiaydogan** [tokland/youtube-upload#195]
Trying to upload video as a standart user, getting the following error:

[ezgi.aydogan@urartu ~]$ youtube-upload --title="test" test.avi --client-secrets=.youtube-upload-credentials.json
Using client secrets: .youtube-upload-credentials.json
Using credentials file: /home/ezgi.aydogan/.youtube-upload-credentials.json
Traceback (most recent call last):
  File "/usr/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/lib/python2.7/site-packages/youtube_upload/main.py", line 261, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/lib/python2.7/site-packages/youtube_upload/lib.py", line 42, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/youtube_upload/main.py", line 255, in main
    run_main(parser, options, args)
  File "/usr/lib/python2.7/site-packages/youtube_upload/main.py", line 174, in run_main
    youtube = get_youtube_handler(options)
  File "/usr/lib/python2.7/site-packages/youtube_upload/main.py", line 160, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "/usr/lib/python2.7/site-packages/youtube_upload/auth/__init__.py", line 39, in get_resource
    credentials = _get_credentials(flow, storage, get_code_callback)
  File "/usr/lib/python2.7/site-packages/youtube_upload/auth/__init__.py", line 28, in _get_credentials
    existing_credentials = storage.get()
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/usr/lib/python2.7/site-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

But when I try to upload the same video as root, the uploading has been completed successfully. 

OS: CentOS 7.3
Progressbar2 version: 3.30.2
google-api-python-client version: 1.6.2
python 2.7 

Thank you.

**Comment by userlip** [comment]
Probably just a permission error with the json file. What permissions does it have?

**Comment by ezgiaydogan** [comment]
I' d tried to give .py files' permissions to spesific standarit user instead of root for accessşing them. But; it didn't matter. Error is the same.

**Comment by avioli** [comment]
I think @userlip meant `.youtube-upload-credentials.json` permissions.
Or even `/home/ezgi.aydogan/.youtube-upload-credentials.json`

**Comment by userlip** [comment]
If desperate just chmod 777 the whole folder - recursively (yea yea security issues & stuff but who cares)
