### ISSUE TITLE
Crash in oauth2client/client.py", line 274, in new_from_json

### ISSUE THREAD

**Issue by xorik** [tokland/youtube-upload#24]
Hi! Just installed, download json by instructions and got this:

```
Using client secrets: /usr/local/share/youtube_upload/client_secrets.json
Using credentials file: /home/xor/google.json
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 181, in <module>
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 37, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/bin/youtube-upload", line 178, in main
    run_main(parser, options, args)
  File "/usr/local/bin/youtube-upload", line 133, in run_main
    get_code_callback=get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth/__init__.py", line 39, in get_resource
    credentials = _get_credentials(flow, storage, get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth/__init__.py", line 28, in _get_credentials
    existing_credentials = storage.get()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client-1.4.7-py2.7.egg/oauth2client/client.py", line 367, in get
    return self.locked_get()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client-1.4.7-py2.7.egg/oauth2client/file.py", line 79, in locked_get
    credentials = Credentials.new_from_json(content)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client-1.4.7-py2.7.egg/oauth2client/client.py", line 274, in new_from_json
    module = data['_module']
KeyError: '_module'
```

**Comment by xorik** [comment]
sorry, without "--credentials-file=" works great!
