### ISSUE TITLE
I suddenly can not upload anymore

### ISSUE THREAD

**Issue by Dreysman** [tokland/youtube-upload#255]
I get this when I try to upload videos using the same command that I have used for uploading dozens of videos.

>Using client secrets: secrets.json
Using credentials file: creds.json

>Using category: Music (id=10)
Start upload: gop.mp4
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/bin/youtube-upload/youtube_upload/main.py", line 261, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/bin/youtube-upload/youtube_upload/lib.py", line 42, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/bin/youtube-upload/youtube_upload/main.py", line 255, in main
    run_main(parser, options, args)
  File "/usr/local/bin/youtube-upload/youtube_upload/main.py", line 178, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)
  File "/usr/local/bin/youtube-upload/youtube_upload/main.py", line 140, in upload_youtube_video
    chunksize=options.chunksize)
  File "/usr/local/bin/youtube-upload/youtube_upload/upload_video.py", line 42, in upload
    RETRIABLE_EXCEPTIONS, max_retries=max_retries)
  File "/usr/local/bin/youtube-upload/youtube_upload/lib.py", line 70, in retriable_exceptions
    return fun()
  File "/usr/local/bin/youtube-upload/youtube_upload/upload_video.py", line 40, in <lambda>
    upload_fun = lambda: _upload_to_request(request, progress_callback)
  File "/usr/local/bin/youtube-upload/youtube_upload/upload_video.py", line 24, in _upload_to_request
    status, response = request.next_chunk()
  File "/Library/Python/2.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/googleapiclient/http.py", line 912, in next_chunk
    self.uri, method=self.method, body=self.body, headers=start_headers)
  File "/Library/Python/2.7/site-packages/googleapiclient/http.py", line 167, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/oauth2client/transport.py", line 186, in new_request
    credentials._refresh(orig_request_method)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: disabled_client: The OAuth client was disabled.
N/A% |#                                                                                                                                                                     |   0.0 s/B

**Comment by bilfr3d** [comment]
Your OAuth token has expired, re-do the steps you initially did for client secret/credential creation

**Comment by ZainRizvi** [comment]
This issue seems like it can be closed

**Comment by Dreysman** [comment]
Yes, will do.
