### ISSUE TITLE
Missing property "redirect_uris" in a client type of "web"

### ISSUE THREAD

**Issue by toneytang** [tokland/youtube-upload#257]
I just start to us the tool. But I got this error. I've no idea what is the reason. 

I am using Python3.7 and Windows 10.

C:\Users\Toney\Desktop\concatena>python C:\Users\Toney\Desktop\concatena\youtube-upload\bin\youtube-upload --title=test xx.mp4
Using client secrets: C:\Users\Toney\.client_secrets.json
Using credentials file: C:\Users\Toney\.youtube-upload-credentials.json
Traceback (most recent call last):
  File "C:\Users\Toney\Desktop\concatena\youtube-upload\bin\youtube-upload", line 10, in <module>
    main.run()
  File "C:\Users\Toney\Desktop\concatena\youtube-upload\bin\..\youtube_upload\main.py", line 257, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "C:\Users\Toney\Desktop\concatena\youtube-upload\bin\..\youtube_upload\lib.py", line 42, in catch_exceptions
    fun(*args, **kwargs)
  File "C:\Users\Toney\Desktop\concatena\youtube-upload\bin\..\youtube_upload\main.py", line 251, in main
    run_main(parser, options, args)
  File "C:\Users\Toney\Desktop\concatena\youtube-upload\bin\..\youtube_upload\main.py", line 170, in run_main
    youtube = get_youtube_handler(options)
  File "C:\Users\Toney\Desktop\concatena\youtube-upload\bin\..\youtube_upload\main.py", line 156, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "C:\Users\Toney\Desktop\concatena\youtube-upload\bin\..\youtube_upload\auth\__init__.py", line 37, in get_resource
    flow = get_flow(client_secrets_file, scope=YOUTUBE_UPLOAD_SCOPE)
  File "C:\Users\Toney\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Toney\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "C:\Users\Toney\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "C:\Users\Toney\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\clientsecrets.py", line 126, in _loadfile
    return _validate_clientsecrets(obj)
  File "C:\Users\Toney\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\clientsecrets.py", line 101, in _validate_clientsecrets
    prop_name, client_type))
oauth2client.clientsecrets.InvalidClientSecretsError: Missing property "redirect_uris" in a client type of "web".

**Comment by toneytang** [comment]
find out the reason. 

The project name and credential name in Google should be English letters. I used Chinese. That caused problem.

solved.
