### ISSUE TITLE
oauth2client.clientsecrets.InvalidClientSecretsError: Missing property "redirect _uris" in a client type of "web".

### ISSUE THREAD

**Issue by ouzkagan** [tokland/youtube-upload#259]
i really don't understand what's problem

`C:\Users\Samsung\Desktop\youtube-upload-master\bin>youtube-upload --title="a" a.
mp4

C:\Users\Samsung\Desktop\youtube-upload-master\bin>python C:\Users\Samsung\Deskt
op\youtube-upload-master\bin\youtube-upload --title="a" a.mp4
Using client secrets: C:\Users\Samsung\.client_secrets.json
Using credentials file: C:\Users\Samsung\.youtube-upload-credentials.json
Traceback (most recent call last):
  File "C:\Users\Samsung\Desktop\youtube-upload-master\bin\youtube-upload", line
 10, in <module>
    main.run()
  File "C:\Users\Samsung\Desktop\youtube-upload-master\bin\..\youtube_upload\mai
n.py", line 257, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "C:\Users\Samsung\Desktop\youtube-upload-master\bin\..\youtube_upload\lib
.py", line 42, in catch_exceptions
    fun(*args, **kwargs)
  File "C:\Users\Samsung\Desktop\youtube-upload-master\bin\..\youtube_upload\mai
n.py", line 251, in main
    run_main(parser, options, args)
  File "C:\Users\Samsung\Desktop\youtube-upload-master\bin\..\youtube_upload\mai
n.py", line 170, in run_main
    youtube = get_youtube_handler(options)
  File "C:\Users\Samsung\Desktop\youtube-upload-master\bin\..\youtube_upload\mai
n.py", line 156, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "C:\Users\Samsung\Desktop\youtube-upload-master\bin\..\youtube_upload\aut
h\__init__.py", line 37, in get_resource
    flow = get_flow(client_secrets_file, scope=YOUTUBE_UPLOAD_SCOPE)
  File "C:\Python27\lib\site-packages\oauth2client\_helpers.py", line 133, in po
sitional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Python27\lib\site-packages\oauth2client\client.py", line 2135, in flo
w_from_clientsecrets
    cache=cache)
  File "C:\Python27\lib\site-packages\oauth2client\clientsecrets.py", line 165,
in loadfile
    return _loadfile(filename)
  File "C:\Python27\lib\site-packages\oauth2client\clientsecrets.py", line 126,
in _loadfile
    return _validate_clientsecrets(obj)
  File "C:\Python27\lib\site-packages\oauth2client\clientsecrets.py", line 101,
in _validate_clientsecrets
    prop_name, client_type))
oauth2client.clientsecrets.InvalidClientSecretsError: Missing property "redirect
_uris" in a client type of "web".`

**Comment by telefoonmaster** [comment]
> i really don't understand what's problem
> 
> `C:\Users\Samsung\Desktop\youtube-upload-master\bin>youtube-upload --title="a" a.
> mp4
> 
> C:\Users\Samsung\Desktop\youtube-upload-master\bin>python C:\Users\Samsung\Deskt
> op\youtube-upload-master\bin\youtube-upload --title="a" a.mp4
> Using client secrets: C:\Users\Samsung.client_secrets.json
> Using credentials file: C:\Users\Samsung.youtube-upload-credentials.json
> Traceback (most recent call last):
> File "C:\Users\Samsung\Desktop\youtube-upload-master\bin\youtube-upload", line
> 10, in 
> main.run()
> File "C:\Users\Samsung\Desktop\youtube-upload-master\bin..\youtube_upload\mai
> n.py", line 257, in run
> sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
> File "C:\Users\Samsung\Desktop\youtube-upload-master\bin..\youtube_upload\lib
> .py", line 42, in catch_exceptions
> fun(*args, **kwargs)
> File "C:\Users\Samsung\Desktop\youtube-upload-master\bin..\youtube_upload\mai
> n.py", line 251, in main
> run_main(parser, options, args)
> File "C:\Users\Samsung\Desktop\youtube-upload-master\bin..\youtube_upload\mai
> n.py", line 170, in run_main
> youtube = get_youtube_handler(options)
> File "C:\Users\Samsung\Desktop\youtube-upload-master\bin..\youtube_upload\mai
> n.py", line 156, in get_youtube_handler
> get_code_callback=get_code_callback)
> File "C:\Users\Samsung\Desktop\youtube-upload-master\bin..\youtube_upload\aut
> h__init__.py", line 37, in get_resource
> flow = get_flow(client_secrets_file, scope=YOUTUBE_UPLOAD_SCOPE)
> File "C:\Python27\lib\site-packages\oauth2client_helpers.py", line 133, in po
> sitional_wrapper
> return wrapped(*args, **kwargs)
> File "C:\Python27\lib\site-packages\oauth2client\client.py", line 2135, in flo
> w_from_clientsecrets
> cache=cache)
> File "C:\Python27\lib\site-packages\oauth2client\clientsecrets.py", line 165,
> in loadfile
> return _loadfile(filename)
> File "C:\Python27\lib\site-packages\oauth2client\clientsecrets.py", line 126,
> in _loadfile
> return _validate_clientsecrets(obj)
> File "C:\Python27\lib\site-packages\oauth2client\clientsecrets.py", line 101,
> in _validate_clientsecrets
> prop_name, client_type))
> oauth2client.clientsecrets.InvalidClientSecretsError: Missing property "redirect
> _uris" in a client type of "web".`

find out the reason.

The project name and credential name in Google should be English letters. I used Chinese. That caused problem.

solved.
Maybe you can answer my question :)

**Comment by lucas19700000** [comment]
Create a Client ID: Add credentials -> OAuth 2.0 Client ID -> Other -> Name: youtube-upload -> Create -> OK

Other
Other
Other
Other

**Comment by bubjavier** [comment]
<img width="800" alt="Screen Shot 2020-03-19 at 10 36 18 PM" src="https://user-images.githubusercontent.com/182977/77078861-20d59a00-6a32-11ea-86f9-df4c70d6518a.png">

not sure "Other" is an option anymore...

**Comment by richard523** [comment]
I believe the new way is now this:
Create Client ID (APIs & Auth -> Credentials -> Create Credentials), select 'Oauth client ID', select type 'Web application'
Add an 'Authorized redirect URI' of 'http://localhost:8080/oauth2callback'
Download the client secrets JSON file (click download icon next to newly created client ID) and save it as file client_secrets.json in the same directory as the utility e.g.

**Comment by cxt532** [comment]
> I believe the new way is now this: Create Client ID (APIs & Auth -> Credentials -> Create Credentials), select 'Oauth client ID', select type 'Web application' Add an 'Authorized redirect URI' of 'http://localhost:8080/oauth2callback' Download the client secrets JSON file (click download icon next to newly created client ID) and save it as file client_secrets.json in the same directory as the utility e.g.

I used your method to generate the client secret json, I ran the normal upload code, the system responded with a link I need to open in my browser to get a verification code

But after I opened the link, it showed the following error

The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type. You can create a Client ID for native application at https://console.developers.google.com/apis/credentials/oauthclient
