### ISSUE TITLE
 does not find the client_secret.json file

### ISSUE THREAD

**Issue by raketenjonny1337** [tokland/youtube-upload#267]
C:\Users\jonny\Desktop\youtube-upload-master\youtube-upload-master\bin>python C:\Users\jonny\Desktop\youtube-upload-master\youtube-upload-master\bin\youtube-upload --title="testvideo" testvideo.mp4
Using client secrets: C:\Users\jonny\.client_secrets.json
Using credentials file: C:\Users\jonny\.youtube-upload-credentials.json
Traceback (most recent call last):
  File "C:\Users\jonny\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\clientsecrets.py", line 121, in _loadfile
    with open(filename, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jonny\\.client_secrets.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonny\Desktop\youtube-upload-master\youtube-upload-master\bin\youtube-upload", line 10, in <module>
    main.run()
  File "C:\Users\jonny\Desktop\youtube-upload-master\youtube-upload-master\bin\..\youtube_upload\main.py", line 268, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "C:\Users\jonny\Desktop\youtube-upload-master\youtube-upload-master\bin\..\youtube_upload\lib.py", line 44, in catch_exceptions
    fun(*args, **kwargs)
  File "C:\Users\jonny\Desktop\youtube-upload-master\youtube-upload-master\bin\..\youtube_upload\main.py", line 262, in main
    run_main(parser, options, args)
  File "C:\Users\jonny\Desktop\youtube-upload-master\youtube-upload-master\bin\..\youtube_upload\main.py", line 176, in run_main
    youtube = get_youtube_handler(options)
  File "C:\Users\jonny\Desktop\youtube-upload-master\youtube-upload-master\bin\..\youtube_upload\main.py", line 162, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "C:\Users\jonny\Desktop\youtube-upload-master\youtube-upload-master\bin\..\youtube_upload\auth\__init__.py", line 37, in get_resource
    flow = get_flow(client_secrets_file, scope=YOUTUBE_UPLOAD_SCOPE)
  File "C:\Users\jonny\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\jonny\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "C:\Users\jonny\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "C:\Users\jonny\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\clientsecrets.py", line 125, in _loadfile
    exc.strerror, exc.errno)
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'C:\\Users\\jonny\\.client_secrets.json', 'No such file or directory', 2)

When I try to upload a video (youtube-upload --title = "testvideo") comes this error message. I downloaded the JSON file and saved it to youtube-upload-master. Then I renamed it to "client_secrets.json". In the file I changed the client_id and client_secret to my data from google api

Thank you!

**Comment by Jaqen00** [comment]
Using client secrets: C:\Users\jonny.client_secrets.json

FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\jonny\.client_secrets.json'

**Comment by wodim** [comment]
Not sure if this is a problem for you anymore, but the file should be named, as the error says: `C:\Users\jonny\.client_secrets.json`

**Comment by kootsoop** [comment]
I was getting this, too, but I had the .client_secerts.json file in the wrong directory, as @wodim comments.  Closing, as you say `I downloaded the JSON file and saved it to youtube-upload-master.` which is the wrong directory for it.
