### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by mfraser** [tokland/youtube-upload#279]
When I tried to upload a video to YouTube today, it fails with "SSL: CERTIFICATE_VERIFY_FAILED" having worked previously.

Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 181, in <module>
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 37, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/bin/youtube-upload", line 178, in main
    run_main(parser, options, args)
  File "/usr/local/bin/youtube-upload", line 133, in run_main
    get_code_callback=get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth/__init__.py", line 39, in get_resource
    credentials = _get_credentials(flow, storage, get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth/__init__.py", line 32, in _get_credentials
    return _get_credentials_interactively(flow, storage, get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth/__init__.py", line 21, in _get_credentials_interactively
    credential = flow.step2_exchange(code, http=None)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 1975, in step2_exchange
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
httplib2.SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

**Comment by kootsoop** [comment]
@mfraser Is this still happening?

**Comment by KenSharp** [comment]
I've seen this after authorisation. Just run it again and all is fine. I suspect something isn't updated instantly in the Google Cache.

**Comment by KenSharp** [comment]
I see this immediately after entering the auth code.

**Comment by KenSharp** [comment]
Okay, I reinstalled `youtube-upload` which pulled in a load of new packages, and this now works. My guess is that the old packages simply don't work anymore and you need to update/upgrade/reinstall to get things working again.
