### ISSUE TITLE
 Missing property "redirect_uris" in a client type of "installed"

### ISSUE THREAD

**Issue by Babakinha** [tokland/youtube-upload#289]
im using win10 if it helps ;-;

C:\Users\Adams\Desktop\youtube-upload-master\bin>youtube-upload --title='test' --client-secret=client_secrets.json /desktop/Untitled.mpg

C:\Users\Adams\Desktop\youtube-upload-master\bin>python C:\Users\Adams\Desktop\youtube-upload-master\bin\youtube-upload --title='test' --client-secret=client_secrets.json /desktop/Untitled.mpg
Using client secrets: client_secrets.json
Using credentials file: C:\Users\Adams\.youtube-upload-credentials.json
Traceback (most recent call last):
  File "C:\Users\Adams\Desktop\youtube-upload-master\bin\youtube-upload", line 10, in <module>
    main.run()
  File "C:\Users\Adams\Desktop\youtube-upload-master\bin\..\youtube_upload\main.py", line 268, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "C:\Users\Adams\Desktop\youtube-upload-master\bin\..\youtube_upload\lib.py", line 44, in catch_exceptions
    fun(*args, **kwargs)
  File "C:\Users\Adams\Desktop\youtube-upload-master\bin\..\youtube_upload\main.py", line 262, in main
    run_main(parser, options, args)
  File "C:\Users\Adams\Desktop\youtube-upload-master\bin\..\youtube_upload\main.py", line 176, in run_main
    youtube = get_youtube_handler(options)
  File "C:\Users\Adams\Desktop\youtube-upload-master\bin\..\youtube_upload\main.py", line 162, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "C:\Users\Adams\Desktop\youtube-upload-master\bin\..\youtube_upload\auth\__init__.py", line 37, in get_resource
    flow = get_flow(client_secrets_file, scope=YOUTUBE_UPLOAD_SCOPE)
  File "C:\Users\Adams\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Adams\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "C:\Users\Adams\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "C:\Users\Adams\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\clientsecrets.py", line 126, in _loadfile
    return _validate_clientsecrets(obj)
  File "C:\Users\Adams\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\clientsecrets.py", line 101, in _validate_clientsecrets
    prop_name, client_type))
oauth2client.clientsecrets.InvalidClientSecretsError: Missing property "redirect_uris" in a client type of "installed".

**Comment by ChillerDragon** [comment]
I had the same Issue when selecting the "Web application" type OAuth-Client-ID. Make sure to select "other".
