### ISSUE TITLE
Error running with any argument ('module' object has no attribute 'openssl_md_meth_names')

### ISSUE THREAD

**Issue by travs** [tokland/youtube-upload#29]
youtube-dl (2014.12.3)
Python 2.7.9

I've used this program successfully before. Recently updated from Python 2.7.8 to Python 2.7.9, so I'm not sure if that's the issue.

[Tried this](https://github.com/tokland/youtube-upload/issues/27#issuecomment-102650008) as a shot in the dark, but no effect.

```
$ youtube-upload somefile.mpg
```
```
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 49, in <module>
    import gdata.service
  File "/Library/Python/2.7/site-packages/gdata/service.py", line 76, in <module>
    import atom.service
  File "/Library/Python/2.7/site-packages/atom/service.py", line 35, in <module>
    import atom.http
  File "/Library/Python/2.7/site-packages/atom/http.py", line 40, in <module>
    import httplib
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 79, in <module>
    import mimetools
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 49, in <module>
    import hashlib as _hashlib
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 138, in <module>
    _hashlib.openssl_md_meth_names)
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'
```

**Comment by tokland** [comment]
Mac OS? Other than a google search, no idea. I found this: https://github.com/Homebrew/homebrew/issues/36346

**Comment by tokland** [comment]
No feedback

**Comment by travs** [comment]
In terms of feedback the linked issue did not address the problem. It's probably something to do with my python installation in general

**Comment by tokland** [comment]
Ok, please report if you find the solution, it will surely help other MacOS users.
