### ISSUE TITLE
AttributeError: 'Http' object has no attribute 'redirect_codes'

### ISSUE THREAD

**Issue by ckuethe** [tokland/youtube-upload#298]
**Describe the bug**
Getting an AttributeError on Raspbian 10 (buster), using httplib2 v0.11.3  and python 3.7.3 as provided by package repositories.

```
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/lib/python3.7/dist-packages/youtube_upload/main.py", line 290, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python3.7/dist-packages/youtube_upload/lib.py", line 44, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/youtube_upload/main.py", line 283, in main
    run_main(parser, options, args)
  File "/usr/local/lib/python3.7/dist-packages/youtube_upload/main.py", line 196, in run_main
    youtube = get_youtube_handler(options)
  File "/usr/local/lib/python3.7/dist-packages/youtube_upload/main.py", line 180, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "/usr/local/lib/python3.7/dist-packages/youtube_upload/auth/__init__.py", line 44, in get_resource
    httplib.redirect_codes = httplib.redirect_codes - {308}
AttributeError: 'Http' object has no attribute 'redirect_codes'
```

**To Reproduce**
youtube-upload $FLAGS test.mp4

**Expected behavior**
I expected to not get an error.

**Desktop (please complete the following information):**
 - System: Raspberry Pi 3B+
 - OS: Raspbian
 - OS Version: 10
 - Python Version: 3.7.3

**Additional context**
In get_resource, I wrapped the redirect_codes stuff in a try/except to make the error go away since it didn't seem to be used for anything

```
    if credentials:
        httplib = httplib2.Http()
        try:
            httplib.redirect_codes = httplib.redirect_codes - {308}
        except AttributeError:
            pass
```

**Comment by ckuethe** [comment]
And the google api library does this try/except too... https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/http.py#L1905

**Comment by postyposty** [comment]
I am getting the same error using python 3.6.8 on Linux Mint. Any solutions?

**Comment by DWegmann** [comment]
You need to select "desktop application" not "web application" as type for the auth application.

**Comment by ckuethe** [comment]
See #297 - I used "desktop application" since "other" is no longer a choice.

**Comment by ayman-roshdy** [comment]
I am getting the same error and I already authenticated my app as 'Desktop application', any new updates here?
Thanks

**Comment by ahmedtds** [comment]
fix please?

**Comment by chriszilla1123** [comment]
Also seeing this issue. Using Python 2.7, oauth verified successfully and is using desktop application type

EDIT: I wrapped the code OP posted in a try/catch block and it's working as expected.

**Comment by geektechniquestudios** [comment]
This worked for me. Seems to be a pretty important change. This should be pulled.

**Comment by mociduki** [comment]
Running the command below solved this issue for my case. Got another issue though, hope it's completely unrelated to this issue..
pip install --upgrade google-api-python-client

**Comment by vigilantspb** [comment]
> 
> 
> Also seeing this issue. Using Python 2.7, oauth verified successfully and is using desktop application type
> 
> EDIT: I wrapped the code OP posted in a try/catch block and it's working as expected.

can you please explain what exactly you did? thanks!

**Comment by sam-ghosh** [comment]
For me it works with Python3.9 but not 3.7
