### ISSUE TITLE
googleapiclient.errors.ResumableUploadError on attempted upload

### ISSUE THREAD

**Issue by Syphere** [tokland/youtube-upload#3]
`youtube-upload --title="TestTitle" --description="TestDescription" TestMovie.avi`

<pre>Traceback (most recent call last):
  File "/usr/bin/youtube-upload", line 211, in <module>
    sys.exit(catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/bin/youtube-upload", line 61, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/bin/youtube-upload", line 208, in main
    run_main(parser, options, args)
  File "/usr/bin/youtube-upload", line 169, in run_main
    video_id = upload_video(youtube, options, video_path, len(args), index)
  File "/usr/bin/youtube-upload", line 145, in upload_video
    progress_callback=progress.callback, chunksize=16*1024)
  File "/usr/lib/python2.7/site-packages/youtube_upload/upload_video.py", line 10, in upload
    status, response = request.next_chunk()
  File "/usr/lib/python2.7/site-packages/oauth2client-1.4.5-py2.7.egg/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/google_api_python_client-1.3.1-py2.7.egg/googleapiclient/http.py", line 808, in next_chunk
    raise ResumableUploadError(resp, content)
googleapiclient.errors.ResumableUploadError: HttpError 400 "Media type 'None' is not supported. Valid media types: [video/*, application/octet-stream]"</pre>

Adding `mimetype='application/octet-stream'` to the proper location in upload_video.py does work, but I am unsure if it has any negative effects during uploading.

**Comment by tokland** [comment]
that's weird, this avi is not recognized as a video by the Youtube API. Anyway, I don't see any problem in what you did, let's avoid this kind of errors: mimetype='application/octet-stream'
