### ISSUE TITLE
terminating with exception KeyError: '_module'

### ISSUE THREAD

**Issue by wrachofsky** [tokland/youtube-upload#31]
Hi, the script is terminating with an exception, I think something having to do with the getting credentials or the credentials file. Any help would be greatly appreciated
I'm running the script with this input 
python main.py  --title="test" --client-secrets=/Users/willrachofsky/youtube-upload/client_secrets.json --credentials-file=/Users/willrachofsky/youtube-upload/credentials_file.json  /Users/willrachofsky/Movies/testforyoutube.mp4
and getting this output
Using client secrets: /Users/willrachofsky/youtube-upload/client_secrets.json
Using credentials file: /Users/willrachofsky/youtube-upload/credentials_file.json
Traceback (most recent call last):
  File "main.py", line 189, in <module>
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_upload/lib.py", line 37, in catch_exceptions
    fun(*args, **kwargs)
  File "main.py", line 186, in main
    run_main(parser, options, args)
  File "main.py", line 141, in run_main
    get_code_callback=get_code_callback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_upload/auth/__init__.py", line 39, in get_resource
    credentials = _get_credentials(flow, storage, get_code_callback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_upload/auth/__init__.py", line 28, in _get_credentials
    existing_credentials = storage.get()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client-1.4.11-py2.7.egg/oauth2client/client.py", line 374, in get
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client-1.4.11-py2.7.egg/oauth2client/file.py", line 79, in locked_get
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client-1.4.11-py2.7.egg/oauth2client/client.py", line 281, in new_from_json
KeyError: '_module'

**Comment by tokland** [comment]
Open the credentials file and check if there is a `_module` key on the JSON. Probably there is not. Delete this file and try again.

**Comment by wrachofsky** [comment]
I do need that file though right? - how do I make it?

**Comment by tokland** [comment]
You don't need it. If the file does not exist, the auth process will begin, and finally the file will be created if successful (so your are not asked again).

**Comment by wrachofsky** [comment]
Now the server is saying I'm not signed in, although I followed all the steps for creating a project on the developers console: this error

Server response was: {
 "error": {
  "errors": [
   {
    "domain": "youtube.header",
    "reason": "youtubeSignupRequired",
    "message": "Unauthorized",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Unauthorized"
 }
}

**Comment by tokland** [comment]
What happens if you try to upload the video with the default secrets file included in the package? If that works, then send me your JSON secrets file to reproduce the problem. (pyarnau AT gmail DOT com).

**Comment by wrachofsky** [comment]
Hi- sorry- yes you are correct it works now

**Comment by tokland** [comment]
great!

**Comment by wrachofsky** [comment]
For my company, I'm trying to get the content-id copyrighting data for videos. This information:
![image](https://cloud.githubusercontent.com/assets/5726487/7846547/329ffb1a-048c-11e5-9ab2-416d75b15697.png)

**Comment by tokland** [comment]
Well, this has nothing to do with the upload, but I guess you can simply parse the copyright page (https://www.youtube.com/copynotice?video_id=ID)
