### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'firefox_options'

### ISSUE THREAD

**Issue by chao-cc** [tokland/youtube-upload#347]
Tokland is not working on youtube-upload anymore. However, @kootsoop is.  If you prepare a PR, we'll gladly merge it. Any help, gratefully received.

**Describe the bug**
TypeError: __init__() got an unexpected keyword argument 'firefox_options'

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. mac m1]
 - OS Version [e.g. 12.3]
 - Python Version [e.g. 3.9.11

**Additional context**
Traceback (most recent call last):
  File "/Users/donny./Documents/PythonProjects/youtube_uploader_selenium/upload.py", line 26, in <module>
    main(video_path, metadata_path, thumbnail_path)
  File "/Users/donny./Documents/PythonProjects/youtube_uploader_selenium/upload.py", line 7, in main
    uploader = YouTubeUploader(video_path, metadata_path, thumbnail_path)
  File "/Users/donny./Documents/PythonProjects/youtube_uploader_selenium/youtube_uploader_selenium/__init__.py", line 33, in __init__
    self.browser = Firefox(current_working_dir, current_working_dir)
  File "/Users/donny./Documents/PythonProjects/youtube_uploader_selenium/venv/lib/python3.9/site-packages/selenium_firefox/firefox.py", line 86, in __init__
    self.driver = webdriver.Firefox(firefox_profile=profile, firefox_options=options)
TypeError: __init__() got an unexpected keyword argument 'firefox_options'

**Comment by AzapiSolutions** [comment]
managed to solve? same problem here

**Comment by R3PO97** [comment]
Same issue, was anyone able to find a fix?

**Comment by R3PO97** [comment]
Whatsup, 


**Error comes up when instantiating selenium's Firefox webdriver -** 

self.driver = webdriver.Firefox(firefox_profile=profile, firefox_options=options) 
TypeError: WebDriver.__init__() got an unexpected keyword argument 'firefox_profile'


**Selenium deprecated 'firefox_options` with Selenium 3.8.0. See below:**
[https://github.com/SeleniumHQ/selenium/blob/4c0404e9580050c488f714885adea712a6f2da0d/py/CHANGES#L368](url)

**Selenium 3.8.0**
* Firefox options can now be imported from selenium.webdriver as FirefoxOptions (#5120)
* Headless mode can now be set in Chrome Options using `set_headless`
* Headless mode can now be set in Firefox Options using `set_headless`
* Add the WebKitGTK WebDriver and options class (#4635)
* Browser options can now be passed to remote WebDriver via the `options` parameter
* Browser option parameters are now standardized across drivers as `options`. `firefox_options`,
  `chrome_options`, and `ie_options` are now deprecated
* Added missing W3C Error Codes (#4556)
* Support has been removed for Python versions 2.6 and 3.3

**Just use Selenium 3.7.0. Worked for me.**
