### ISSUE TITLE
httplib2.RedirectMissingLocation: Redirected but the response is missing a Location: header.

### ISSUE THREAD

**Issue by tharsdim** [tokland/youtube-upload#357]
Not sure what is wrong here. This used to run for two years and suddenly i get this one...

Any help appreciated

pi@raspberrypi:~ $ python /home/pi/PythonScripts/timelapse/youtube-upload-master/bin/youtube-upload /home/pi/PythonScripts/timelapse/youtube-upload-master/bin/test.mp4 --title="xaxxadescription" --description="description" --privacy=unlisted --publish-at="2022-10-10T09:22:58+03:00" --client-secrets=/home/pi/PythonScripts/client_secrets.json
Using client secrets: /home/pi/PythonScripts/client_secrets.json
Using credentials file: /home/pi/.youtube-upload-credentials2.json
Your video will remain private until specified date.
Start upload: /home/pi/PythonScripts/timelapse/youtube-upload-master/bin/test.mp4
Traceback (most recent call last):
  File "/home/pi/PythonScripts/timelapse/youtube-upload-master/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/home/pi/PythonScripts/timelapse/youtube-upload-master/bin/../youtube_upload/main.py", line 269, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/home/pi/PythonScripts/timelapse/youtube-upload-master/bin/../youtube_upload/lib.py", line 44, in catch_exceptions
    fun(*args, **kwargs)
  File "/home/pi/PythonScripts/timelapse/youtube-upload-master/bin/../youtube_upload/main.py", line 263, in main
    run_main(parser, options, args)
  File "/home/pi/PythonScripts/timelapse/youtube-upload-master/bin/../youtube_upload/main.py", line 181, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)
  File "/home/pi/PythonScripts/timelapse/youtube-upload-master/bin/../youtube_upload/main.py", line 147, in upload_youtube_video
    chunksize=options.chunksize)
  File "/home/pi/PythonScripts/timelapse/youtube-upload-master/bin/../youtube_upload/upload_video.py", line 43, in upload
    RETRIABLE_EXCEPTIONS, max_retries=max_retries)
  File "/home/pi/PythonScripts/timelapse/youtube-upload-master/bin/../youtube_upload/lib.py", line 76, in retriable_exceptions
    raise exc
httplib2.RedirectMissingLocation: Redirected but the response is missing a Location: header.

**Comment by tharsdim** [comment]
closing
