### ISSUE TITLE
Progressbar error

### ISSUE THREAD

**Issue by kangoo13** [tokland/youtube-upload#37]
Hello, I have got this error when trying to upload :  

```
root@hostname:/youtube-upload# /youtube-upload/bin/youtube-upload -t DESCRIPTION -d d /clip.mp4
Using client secrets: /usr/local/share/youtube_upload/client_secrets.json
Using credentials file: /root/.youtube-upload-credentials.json
Start upload: /clip.mp4 (DESCRIPTION)
Traceback (most recent call last):
  File "/youtube-upload/bin/youtube-upload", line 192, in <module>
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 37, in catch_exceptions
    fun(*args, **kwargs)
  File "/youtube-upload/bin/youtube-upload", line 189, in main
    run_main(parser, options, args)
  File "/youtube-upload/bin/youtube-upload", line 146, in run_main
    video_id = upload_video(youtube, options, video_path, len(args), index)
  File "/youtube-upload/bin/youtube-upload", line 117, in upload_video
    progress.finish()
  File "/usr/local/lib/python2.7/dist-packages/progressbar/__init__.py", line 320, in finish
    self.update(self.maxval)
  File "/usr/local/lib/python2.7/dist-packages/progressbar/__init__.py", line 276, in update
    if not self._need_update(): return
  File "/usr/local/lib/python2.7/dist-packages/progressbar/__init__.py", line 251, in _need_update
    if self.currval >= self.next_update or self.finished: return True
AttributeError: next_update
```

**Comment by tokland** [comment]
Indeed, it failed for small files when the bar was not yet initialitzed. Fixed: 34ad9fc. thx!
