### ISSUE TITLE
upload video but got ResumableUploadError with HttpError 401 "Unauthorized"

### ISSUE THREAD

**Issue by cdotchen** [tokland/youtube-upload#5]
`youtube-upload --title="test" --location="=" video.mp4`

```
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 164, in <module>
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/Library/Python/2.7/site-packages/youtube_upload/lib.py", line 21, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/bin/youtube-upload", line 161, in main
    run_main(parser, options, args)
  File "/usr/local/bin/youtube-upload", line 124, in run_main
    video_id = upload_video(youtube, options, video_path, len(args), index)
  File "/usr/local/bin/youtube-upload", line 100, in upload_video
    progress_callback=progress.callback, chunksize=16*1024)
  File "/Library/Python/2.7/site-packages/youtube_upload/upload_video.py", line 58, in upload
    return _upload_to_request(request, progress_callback)
  File "/Library/Python/2.7/site-packages/youtube_upload/upload_video.py", line 24, in _wrapper
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/youtube_upload/upload_video.py", line 43, in _upload_to_request
    status, response = request.next_chunk()
  File "/Library/Python/2.7/site-packages/oauth2client-1.4.6-py2.7.egg/oauth2client/util.py", line 135, in positional_wrapper
  File "/Library/Python/2.7/site-packages/google_api_python_client-1.3.1-py2.7.egg/googleapiclient/http.py", line 808, in next_chunk
googleapiclient.errors.ResumableUploadError: <HttpError 401 "Unauthorized">
```

**Comment by cdotchen** [comment]
To resolve this:
1. delete `~/.youtube-upload-credentials.json`
2. re-auth by `youtube-upload --title="test" --location="=" video.mp4`
3. if you have multiple google accounts, pick one which enabled youtube creator studio
