### ISSUE TITLE
Detaching from console, Ctrl+C not working

### ISSUE THREAD

**Issue by sezeryalcin** [tokland/youtube-upload#76]
I noticed that script is detaching from console while uploading. This may be desired for certain people but normally it should not do it.

It should not detach from console by default and if possible, detach option can be added as a command line parameter. This will give flexibility to all users.

**Comment by tokland** [comment]
If it does that, it's not intentional, the script should never detach from console, it exits at the end, when the video has been uploaded and we have its ID. Maybe related with python-progressbar? I'd need more info, cannot reproduce.

**Comment by sezeryalcin** [comment]
When I hit Ctrl+C, it returns to bash but progressbar is still working. Then I checked process and it was running. I will help you further with some extra information. Detaching looks like happening after I hit ctrl+c. Are there any signal handlers in this code?
I am using Ubuntu 14.04 x64 with latest updates.

**Comment by tokland** [comment]
The point to check is this:

```
    try:
        video_id = upload_video.upload(youtube, video_path, 
            request_body, progress_callback=progress.callback)
    finally:
        progress.finish()
```

A control+ should raise a KeyboardInterrupt and enter the finally block. Tested with python2 and python3, it works for me. (python-progressbar v2.3)

**Comment by sezeryalcin** [comment]
I misspoke about environment. This is on arm/raspberry pi using ubuntu 14.04 image.
I will try again and see how it behaves and report back.

**Comment by sezeryalcin** [comment]
Here is some debug info. It looks like when I hit Ctrl+C, it returns to shell but process continues in background. It's like forking and becoming daemon in background but STDOUT is still attached to terminal.
It continues to work until I kill it. So There is probably a signal handler picking up Ctrl-C and doing a fork.

Here is full output:

Using client secrets: /root/.client_secrets.json
Using credentials file: /root/.youtube-upload-credentials.json
Start upload: ../videos/file.mp4
  0% |                                                                                               | ETA:  --:--:--   0.00  B/s


^C1% |#                                                                                               | ETA:  0:12:18 520.74 kB/s
100% |################################################################################################| Time: 0:00:08  44.00 MB/s
Traceback (most recent call last):
  File "bin/youtube-upload", line 10, in <module>
root@kurtkoy:~#     main.run()
  File "/SECURE/youtube/youtube-upload/youtube_upload/main.py", line 236, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/SECURE/youtube/youtube-upload/youtube_upload/lib.py", line 44, in catch_exceptions
    fun(*args, **kwargs)
  File "/SECURE/youtube/youtube-upload/youtube_upload/main.py", line 233, in main
    run_main(parser, options, args)
  File "/SECURE/youtube/youtube-upload/youtube_upload/main.py", line 174, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)
  File "/SECURE/youtube/youtube-upload/youtube_upload/main.py", line 134, in upload_youtube_video
    request_body, progress_callback=progress.callback)
  File "/SECURE/youtube/youtube-upload/youtube_upload/upload_video.py", line 40, in upload
    RETRIABLE_EXCEPTIONS, max_retries=max_retries)
  File "/SECURE/youtube/youtube-upload/youtube_upload/lib.py", line 76, in retriable_exceptions
    return fun()
  File "/SECURE/youtube/youtube-upload/youtube_upload/upload_video.py", line 38, in <lambda>
    upload_fun = lambda: _upload_to_request(request, progress_callback)
  File "/SECURE/youtube/youtube-upload/youtube_upload/upload_video.py", line 22, in _upload_to_request
    status, response = request.next_chunk()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 873, in next_chunk
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 596, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1273, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 839, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 808, in send
    self.sock.sendall(datablock)
  File "/usr/lib/python2.7/ssl.py", line 329, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.7/ssl.py", line 298, in send
    v = self._sslobj.write(data)
KeyboardInterrupt
Deleting in 5 seconds...
^C
root@kurtkoy:~# Using client secrets: /root/.client_secrets.json
Using credentials file: /root/.youtube-upload-credentials.json
Start upload: ../videos/file.mp4
^C0% |                                                                                                | ETA:  0:12:10   2.01 MB/s
root@kurtkoy:~#   0% |                                                                                                | ETA:  0:2^C09 868.28 kB/s
root@kurtkoy:~#   0% |                                                                                                | ETA:  0:3^C02 677.94 kB/s
root@kurtkoy:~#   0% |                                                                                                | ETA:  0:4^C54 582.75 kB/s
root@kurtkoy:~#   0% |                                                                                                | ETA:  0:4^C0% |                                                                                                | ETA:  0:49:38 490.80 kB/s
root@kurtkoy:~# ^C
root@kurtkoy:~# ^C
root@kurtkoy:~#   0% |                                                                                                | ETA:  0:5p  0% |                                                                                                | ETA:  0:52:24 464.20 kB/s aux | grep  0% |                                                                                                | ETA:  0:53:12 youtu  0% |                                                                                                | ETA:  0:53:05 457.6bekB/s
root     31761  0.0  0.2   5380  2232 pts/1    S    23:22   0:00 /bin/bash /SECURE/youtube/youtube-upload/loop_mp4
root     31783  9.2  1.5  19628 14780 pts/1    D    23:23   0:02 python bin/youtube-upload --title=carf-2015-12-13_12:00:00 ../videos/file.mp4
root     31787  0.0  0.1   4996  1508 pts/1    S+   23:23   0:00 grep --color=auto youtube
root@kurtkoy:~# kill -  0% |                                                                                                | ETA9   0% |                                                                                                | ETA:  0:57:09 424.43 kB318  1% |#                                                                                               | ETA:  0:55:57 431.09 k783  1% |#                                                                                               | ETA:  0:56:05 429.43 kB/s
root@kurtkoy:~# /SECURE/youtube/youtube-upload/loop_mp4: line 5: 31783 Killed                  PYTHONPATH=. python bin/youtube-upload --title="$TITLE" $f
Deleting in 5 seconds...
^C
root@kurtkoy:~#

**Comment by sezeryalcin** [comment]
Here is some debug info. It looks like when I hit Ctrl+C, it returns to shell but process continues in background. It's like forking and becoming daemon in background but STDOUT is still attached to terminal.
It continues to work until I kill it. So There is probably a signal handler picking up Ctrl-C and doing a fork.

Here is full output:

Using client secrets: /root/.client_secrets.json
Using credentials file: /root/.youtube-upload-credentials.json
Start upload: ../videos/file.mp4
  0% |                                                                                               | ETA:  --:--:--   0.00  B/s


^C1% |#                                                                                               | ETA:  0:12:18 520.74 kB/s
100% |################################################################################################| Time: 0:00:08  44.00 MB/s
Traceback (most recent call last):
  File "bin/youtube-upload", line 10, in <module>
root@kurtkoy:~#     main.run()
  File "/SECURE/youtube/youtube-upload/youtube_upload/main.py", line 236, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/SECURE/youtube/youtube-upload/youtube_upload/lib.py", line 44, in catch_exceptions
    fun(*args, **kwargs)
  File "/SECURE/youtube/youtube-upload/youtube_upload/main.py", line 233, in main
    run_main(parser, options, args)
  File "/SECURE/youtube/youtube-upload/youtube_upload/main.py", line 174, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)
  File "/SECURE/youtube/youtube-upload/youtube_upload/main.py", line 134, in upload_youtube_video
    request_body, progress_callback=progress.callback)
  File "/SECURE/youtube/youtube-upload/youtube_upload/upload_video.py", line 40, in upload
    RETRIABLE_EXCEPTIONS, max_retries=max_retries)
  File "/SECURE/youtube/youtube-upload/youtube_upload/lib.py", line 76, in retriable_exceptions
    return fun()
  File "/SECURE/youtube/youtube-upload/youtube_upload/upload_video.py", line 38, in <lambda>
    upload_fun = lambda: _upload_to_request(request, progress_callback)
  File "/SECURE/youtube/youtube-upload/youtube_upload/upload_video.py", line 22, in _upload_to_request
    status, response = request.next_chunk()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 873, in next_chunk
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 596, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1273, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 839, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 808, in send
    self.sock.sendall(datablock)
  File "/usr/lib/python2.7/ssl.py", line 329, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.7/ssl.py", line 298, in send
    v = self._sslobj.write(data)
KeyboardInterrupt
Deleting in 5 seconds...
^C
root@kurtkoy:~# Using client secrets: /root/.client_secrets.json
Using credentials file: /root/.youtube-upload-credentials.json
Start upload: ../videos/file.mp4
^C0% |                                                                                                | ETA:  0:12:10   2.01 MB/s
root@kurtkoy:~#   0% |                                                                                                | ETA:  0:2^C09 868.28 kB/s
root@kurtkoy:~#   0% |                                                                                                | ETA:  0:3^C02 677.94 kB/s
root@kurtkoy:~#   0% |                                                                                                | ETA:  0:4^C54 582.75 kB/s
root@kurtkoy:~#   0% |                                                                                                | ETA:  0:4^C0% |                                                                                                | ETA:  0:49:38 490.80 kB/s
root@kurtkoy:~# ^C
root@kurtkoy:~# ^C
root@kurtkoy:~#   0% |                                                                                                | ETA:  0:5p  0% |                                                                                                | ETA:  0:52:24 464.20 kB/s aux | grep  0% |                                                                                                | ETA:  0:53:12 youtu  0% |                                                                                                | ETA:  0:53:05 457.6bekB/s
root     31761  0.0  0.2   5380  2232 pts/1    S    23:22   0:00 /bin/bash /SECURE/youtube/youtube-upload/loop_mp4
root     31783  9.2  1.5  19628 14780 pts/1    D    23:23   0:02 python bin/youtube-upload --title=carf-2015-12-13_12:00:00 ../videos/file.mp4
root     31787  0.0  0.1   4996  1508 pts/1    S+   23:23   0:00 grep --color=auto youtube
root@kurtkoy:~# kill -  0% |                                                                                                | ETA9   0% |                                                                                                | ETA:  0:57:09 424.43 kB318  1% |#                                                                                               | ETA:  0:55:57 431.09 k783  1% |#                                                                                               | ETA:  0:56:05 429.43 kB/s
root@kurtkoy:~# /SECURE/youtube/youtube-upload/loop_mp4: line 5: 31783 Killed                  PYTHONPATH=. python bin/youtube-upload --title="$TITLE" $f
Deleting in 5 seconds...
^C
root@kurtkoy:~#

**Comment by sezeryalcin** [comment]
In above case, I hit Ctrl+C and it continues. Then I hit several times more but same thing.
Then I type ps aux | grep youtube and kill -9 PID and then it really stops.

**Comment by tokland** [comment]
If the package progressbar is uninstalled, does control+c work as expected?

**Comment by tokland** [comment]
*Bump*

**Comment by sezeryalcin** [comment]
Yes, I just had time to test again. Uninstalled progressbar and now it does stop and quit the script.

So either progressbar is broken or some parameters needs to be adjusted to actually die when ctrl+c is caught.

I hope this helps to figure it out. I am fine without progressbar. If you fix it somehow, I may install it back.

Using client secrets: /root/.client_secrets.json
Using credentials file: /root/.youtube-upload-credentials.json
Start upload: ../videos/abc.mp4
^CTraceback (most recent call last):
  File "bin/youtube-upload", line 10, in <module>
    main.run()
  File "/SECURE/youtube/youtube-upload/youtube_upload/main.py", line 236, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/SECURE/youtube/youtube-upload/youtube_upload/lib.py", line 44, in catch_exceptions
    fun(*args, **kwargs)
  File "/SECURE/youtube/youtube-upload/youtube_upload/main.py", line 233, in main
    run_main(parser, options, args)
  File "/SECURE/youtube/youtube-upload/youtube_upload/main.py", line 174, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)
  File "/SECURE/youtube/youtube-upload/youtube_upload/main.py", line 134, in upload_youtube_video
    request_body, progress_callback=progress.callback)
  File "/SECURE/youtube/youtube-upload/youtube_upload/upload_video.py", line 40, in upload
    RETRIABLE_EXCEPTIONS, max_retries=max_retries)
  File "/SECURE/youtube/youtube-upload/youtube_upload/lib.py", line 76, in retriable_exceptions
    return fun()
  File "/SECURE/youtube/youtube-upload/youtube_upload/upload_video.py", line 38, in <lambda>
    upload_fun = lambda: _upload_to_request(request, progress_callback)
  File "/SECURE/youtube/youtube-upload/youtube_upload/upload_video.py", line 22, in _upload_to_request
    status, response = request.next_chunk()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 873, in next_chunk
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 596, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1273, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 839, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 808, in send
    self.sock.sendall(datablock)
  File "/usr/lib/python2.7/ssl.py", line 329, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.7/ssl.py", line 298, in send
    v = self._sslobj.write(data)
KeyboardInterrupt

**Comment by sezeryalcin** [comment]
Instead of progressbar, (or if it's not installed) You can add a simple function to print progress. Here I recently made one in PHP in 10 minutes and working great. Easy to port to python and doesn't mess with ctrl+c:

function print_progress($total, $done, $length = 50)
{
  static $ts;  // Start time kept constant

  if (!$ts) $ts = time();

  $elapsed_time   = time() - $ts;
  $total_time     = floor($elapsed_time / ($done / $total));
  $remaining_time = $total_time - $elapsed_time;

  echo "\r"; // come back
  echo "=== ".round($done / $total * 100, 2)."% complete === $done of $total completed === $remaining_time seconds left ===";
  flush();

}

**Comment by tokland** [comment]
I have added support for progressbar2: 9544cf9

Uninstall progressbar and try progressbar2.

**Comment by sezeryalcin** [comment]
Thank you very much for the effort. I will try soon and give you feedback.
