### ISSUE TITLE
Check for upload status sometimes fails

### ISSUE THREAD

**Issue by Konstantinusz** [tokland/youtube-upload#8]
Traceback (most recent call last):
  File "/usr/bin/youtube-upload", line 519, in <module>
    sys.exit(catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/bin/youtube-upload", line 111, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/bin/youtube-upload", line 516, in main
    run_main(parser, options, args)
  File "/usr/bin/youtube-upload", line 449, in run_main
    url = upload_video(youtube, options, video_path, len(args), index)
  File "/usr/bin/youtube-upload", line 379, in upload_video
    wait_processing(youtube, video_id)
  File "/usr/bin/youtube-upload", line 325, in wait_processing
    response = youtube_obj.check_upload_status(video_id)
  File "/usr/bin/youtube-upload", line 254, in check_upload_status
    return self.service.CheckUploadStatus(video_id=video_id)
  File "/usr/lib/python2.7/site-packages/gdata/youtube/service.py", line 687, in CheckUploadStatus
    video_entry = self.GetYouTubeVideoEntry(video_id=video_id)
  File "/usr/lib/python2.7/site-packages/gdata/youtube/service.py", line 210, in GetYouTubeVideoEntry
    return self.Get(uri, converter=gdata.youtube.YouTubeVideoEntryFromString)
  File "/usr/lib/python2.7/site-packages/gdata/service.py", line 1108, in Get
    'reason': server_response.reason, 'body': result_body}
gdata.service.RequestError: {'status': 503, 'body': 'Service Unavailable', 'reason': 'Service Unavailable'}

**Comment by tokland** [comment]
This must be from the old google-code, there is no check_upload_status in the new code. Closing.
