### ISSUE TITLE
Uploading a video results in TypeError

### ISSUE THREAD

**Issue by moritzmar** [tokland/youtube-upload#81]
Uploading a video results in a TypeError. Tested on Archlinux with python2 and python3 aswell on debian 8 with python2

b'Start upload: fut_schn.mp4'
Traceback (most recent call last):
  File "/usr/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/lib/python3.5/site-packages/youtube_upload/main.py", line 243, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/lib/python3.5/site-packages/youtube_upload/lib.py", line 44, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/youtube_upload/main.py", line 238, in main
    run_main(parser, options, args)
  File "/usr/lib/python3.5/site-packages/youtube_upload/main.py", line 176, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)
  File "/usr/lib/python3.5/site-packages/youtube_upload/main.py", line 138, in upload_youtube_video
    request_body, progress_callback=progress.callback)
  File "/usr/lib/python3.5/site-packages/youtube_upload/upload_video.py", line 40, in upload
    RETRIABLE_EXCEPTIONS, max_retries=max_retries)
  File "/usr/lib/python3.5/site-packages/youtube_upload/lib.py", line 76, in retriable_exceptions
    return fun()
  File "/usr/lib/python3.5/site-packages/youtube_upload/upload_video.py", line 38, in <lambda>
    upload_fun = lambda: _upload_to_request(request, progress_callback)
  File "/usr/lib/python3.5/site-packages/youtube_upload/upload_video.py", line 29, in _upload_to_request
    progress_callback(status.total_size, status.resumable_progress)
TypeError: <lambda>() takes 0 positional arguments but 2 were given

**Comment by tokland** [comment]
Fixed, thx! de053cd
