### ISSUE TITLE
'ascii' codec can't decode

### ISSUE THREAD

**Issue by dR3b** [tokland/youtube-upload#85]
Hi,

I had this error today: Uploading a video with german "Umlaut <ü>":
```bash
Using client secrets: /home/user1/youtube/youtube-upload/client_secrets.json
Using credentials file: /home/user1/.youtube-upload-credentials.json
Your video will remain private until specified date.
Using category: Gaming (id=20)
Traceback (most recent call last):
  File "/home/user1/youtube/youtube-upload/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/home/user1/youtube/youtube-upload/bin/../youtube_upload/main.py", line 251, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/home/user1/youtube/youtube-upload/bin/../youtube_upload/lib.py", line 49, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/home/user1/youtube/youtube-upload/bin/../youtube_upload/main.py", line 246, in main
    run_main(parser, options, args)
  File "/usr/home/user1/youtube/youtube-upload/bin/../youtube_upload/main.py", line 178, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)
  File "/usr/home/user1/youtube/youtube-upload/bin/../youtube_upload/main.py", line 137, in upload_youtube_video
    debug("Start upload: {0}".format(video_path))
  File "/usr/home/user1/youtube/youtube-upload/bin/../youtube_upload/lib.py", line 36, in debug
    if should_encode else obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 60: ordinal not in range(128)
```

**Comment by tokland** [comment]
@Skylion007 , any idea?

**Comment by kataste** [comment]
Hi, i have the same problem since two days

"UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1473: ordinal not in range(128)"

**Comment by tokland** [comment]
Function "debug" refactored, tested in 2 and 3, hope it works for you guys.
