### ISSUE TITLE
python: abrt: detected unhandled Python exception in /usr/bin/youtube-upload

### ISSUE THREAD

**Issue by j3dd4h** [tokland/youtube-upload#9]
Sometime the upload was failed due to python crash
========================
Jan 27 16:11:44 user python: abrt: detected unhandled Python exception in /usr/bin/youtube-upload
Jan 27 16:11:44 user abrtd: dumpsocket: New client connected
Jan 27 16:11:44 user abrtd: dumpsocket: Saved Python crash dump of pid 28877 to /var/spool/abrt/pyhook-1422349904-28877
Jan 27 16:11:44 user abrtd: dumpsocket: Socket client disconnected
Jan 27 16:11:44 user abrtd: Directory 'pyhook-1422349904-28877' creation detected
Jan 27 16:11:44 user abrtd: Executable '/usr/bin/youtube-upload' doesn't belong to any package
Jan 27 16:11:44 user abrtd: Corrupted or bad crash /var/spool/abrt/pyhook-1422349904-28877 (res:4), deleting
========================

**Comment by j3dd4h** [comment]
Traceback (most recent call last):
  File "/usr/bin/youtube-upload", line 164, in <module>
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/lib/python2.6/site-packages/youtube_upload/lib.py", line 21, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/bin/youtube-upload", line 161, in main
    run_main(parser, options, args)
  File "/usr/bin/youtube-upload", line 124, in run_main
    video_id = upload_video(youtube, options, video_path, len(args), index)
  File "/usr/bin/youtube-upload", line 100, in upload_video
    progress_callback=progress.callback, chunksize=16*1024)
  File "/usr/lib/python2.6/site-packages/youtube_upload/upload_video.py", line 58, in upload
    return _upload_to_request(request, progress_callback)
  File "/usr/lib/python2.6/site-packages/youtube_upload/upload_video.py", line 24, in _wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/youtube_upload/upload_video.py", line 43, in _upload_to_request
    status, response = request.next_chunk()
  File "/usr/lib/python2.6/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/googleapiclient/http.py", line 874, in next_chunk
    return self._process_response(resp, content)
  File "/usr/lib/python2.6/site-packages/googleapiclient/http.py", line 901, in _process_response
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 503 when requesting https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&alt=json&part=snippet%2Cstatus%2CrecordingDetails returned "Service Unavailable">

**Comment by j3dd4h** [comment]
googleapiclient.errors.HttpError: <HttpError 503 when requesting https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&alt=json&part=snippet%2Cstatus%2CrecordingDetails returned "Service Unavailable">
